refactor(rp): patch shibboleth2.xml in the entrypoint

diff --git a/rp/httpd-foreground b/rp/httpd-foreground
--- a/rp/httpd-foreground
+++ b/rp/httpd-foreground
@@ -18,6 +18,20 @@ fi
 chown -R _shibd:_shibd /var/cache/shibboleth
 
 if [[ -z "$EZMESURE_DISABLE_SHIBBOLETH" ]]; then
+  if [[ ! -v SHIBBOLETH_SP_URL ]]; then
+    echo "Missing env: SHIBBOLETH_SP_URL"
+    exit 1
+  fi
+  if [[ ! -v SHIBBOLETH_DS_URL ]]; then
+    echo "Missing env: SHIBBOLETH_DS_URL"
+    exit 1
+  fi
+
+  # patch shibboleth2.xml config file with SP/DS URLs
+  sed -e "s|{{SHIBBOLETH_SP_URL}}|${SHIBBOLETH_SP_URL}|" \
+      -e "s|{{SHIBBOLETH_DS_URL}}|${SHIBBOLETH_DS_URL}|" \
+      /etc/shibboleth/shibboleth2.dist.xml > /etc/shibboleth/shibboleth2.xml
+
   /etc/init.d/shibd start
 fi
 
